#!/bin/bash
#SBATCH --job-name=fastq_dump_split_xanadu
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --mem=15G
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-type=ALL
#SBATCH --mail-user=tingting.zhao@uconn.edu
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

echo `hostname`

#################################################################
# Download fastq files from SRA
#################################################################
module load sratoolkit/2.8.2

fastq-dump --gzip --split-3 SRR2558714
fastq-dump --gzip --split-3 SRR2558715
fastq-dump --gzip --split-3 SRR2558718
fastq-dump --gzip --split-3 SRR2558719

#################################################################
# Rename the files
#################################################################

