#!/bin/bash
#SBATCH --job-name=fastqc_raw
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --mem=10G
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-type=ALL
#SBATCH --mail-user=zequan.wang@uconn.edu
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

echo `hostname`

#################################################################
# FASTQC of raw reads
#################################################################
dir="before"
if [ ! -d "$dir" ]; then
        mkdir -p $dir
fi

module load fastqc/0.11.7
fastqc --outdir ./"$dir"/ ../data/SRR2558714_1.fastq.gz
fastqc --outdir ./"$dir"/ ../data/SRR2558714_2.fastq.gz
fastqc --outdir ./"$dir"/ ../data/SRR2558715_1.fastq.gz
fastqc --outdir ./"$dir"/ ../data/SRR2558715_2.fastq.gz
fastqc --outdir ./"$dir"/ ../data/SRR2558718_1.fastq.gz
fastqc --outdir ./"$dir"/ ../data/SRR2558718_2.fastq.gz
fastqc --outdir ./"$dir"/ ../data/SRR2558719_1.fastq.gz
fastqc --outdir ./"$dir"/ ../data/SRR2558719_2.fastq.gz


