#!/bin/bash
#SBATCH --job-name=hisat2_index
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 16
#SBATCH --mem=20G
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-type=ALL
#SBATCH --mail-user=zequan.wang@uconn.edu
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

echo `hostname`

#################################################################
# Download the Genome
#################################################################

# download it
wget ftp://ftp.ensembl.org/pub/grch37/release-103/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.chromosome.*.fa.gz

# decompress it
gunzip Homo_sapiens.GRCh37.dna.chromosome.*.fa.gz

# concat it
cat Homo_sapiens.GRCh37.dna.chromosome.*.fa > all.fa
#################################################################
# Indexing the Genome
#################################################################

module load hisat2/2.2.0

hisat2-build -p 16 all.fa GRCh37
